# Generated by Django 3.2.5 on 2021-07-23 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('price', models.IntegerField(null=True)),
                ('off_percentage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_available', models.IntegerField(choices=[(0, 'UnAvailable'), (1, 'Available')])),
                ('count', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('information', models.TextField(null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='items')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='items')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='items')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='items')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='items')),
                ('categories', models.ManyToManyField(blank=True, to='Karl_Shop.Category')),
                ('sizes', models.ManyToManyField(blank=True, to='Karl_Shop.Sizes')),
            ],
        ),
    ]
