# Generated by Django 3.2.5 on 2021-07-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizes',
            name='size',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
