# Generated by Django 3.2.5 on 2021-07-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0002_alter_sizes_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizes',
            options={'ordering': ['size']},
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='price',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
