# Generated by Django 3.2.5 on 2021-07-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0003_auto_20210723_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitems',
            name='image1',
            field=models.ImageField(null=True, upload_to='items'),
        ),
    ]
