# Generated by Django 3.2.5 on 2021-07-23 14:00

import Karl_Shop.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0004_alter_shopitems_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitems',
            name='image1',
            field=models.ImageField(null=True, upload_to=Karl_Shop.models.image_path),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=Karl_Shop.models.image_path),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=Karl_Shop.models.image_path),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=Karl_Shop.models.image_path),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=Karl_Shop.models.image_path),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='off_percentage',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
