# Generated by Django 3.2.5 on 2021-07-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0005_auto_20210723_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitems',
            name='image5',
        ),
    ]
