# Generated by Django 3.2.5 on 2021-07-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0008_auto_20210724_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description(optional)'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='link(optional)'),
        ),
    ]
