# Generated by Django 3.2.5 on 2021-07-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0018_alter_shopitems_off_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='offers/<function image_path at 0x00000189969DD790>')),
                ('link', models.URLField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='image1',
            field=models.ImageField(null=True, upload_to='blog/<function image_path at 0x00000189969DD790>'),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='blog/<function image_path at 0x00000189969DD790>'),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='blog/<function image_path at 0x00000189969DD790>'),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='blog/<function image_path at 0x00000189969DD790>'),
        ),
    ]
