# Generated by Django 3.2.5 on 2021-07-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0019_auto_20210725_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageoffers',
            name='image',
            field=models.ImageField(upload_to='offers/<function image_path at 0x000001D572183820>'),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='image1',
            field=models.ImageField(null=True, upload_to='blog/<function image_path at 0x000001D572183820>'),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='blog/<function image_path at 0x000001D572183820>'),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='blog/<function image_path at 0x000001D572183820>'),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='blog/<function image_path at 0x000001D572183820>'),
        ),
    ]
