# Generated by Django 3.2.5 on 2021-07-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0022_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
