# Generated by Django 3.2.5 on 2021-07-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0023_order_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='is paid'),
        ),
    ]
