# Generated by Django 3.2.5 on 2021-07-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0026_order_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
