# Generated by Django 3.2.5 on 2021-07-26 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0028_auto_20210726_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Karl_Shop.shopitems'),
            preserve_default=False,
        ),
    ]
