# Generated by Django 3.2.5 on 2021-07-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0029_auto_20210726_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitems',
            name='price_after_off',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='final Price (dont change it)'),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
