# Generated by Django 3.2.5 on 2021-07-26 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0030_auto_20210726_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitems',
            name='off_percentage',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='off_percentage(optional)'),
        ),
    ]
