# Generated by Django 3.2.5 on 2021-07-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0031_alter_shopitems_off_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
