# Generated by Django 3.2.5 on 2021-07-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0033_alter_shopitems_price_after_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
