# Generated by Django 3.2.5 on 2021-07-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0034_alter_order_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitems',
            name='price_after_off',
            field=models.IntegerField(blank=True, null=True, verbose_name='final Price (dont change it)'),
        ),
    ]
