# Generated by Django 3.2.5 on 2021-07-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0035_alter_shopitems_price_after_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
