# Generated by Django 3.2.5 on 2021-07-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0039_alter_coupons_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='is_used',
            field=models.IntegerField(choices=[(1, 'not Used'), (0, 'Used')]),
        ),
    ]
