# Generated by Django 3.2.5 on 2021-08-09 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Karl_Shop', '0041_alter_coupons_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Karl_Shop.sizes'),
        ),
    ]
